language: r
# cache: packages
dist: trusty

r_packages:
  - dplyr
  - tidyr
  - latex2exp

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - richelbilderbeek/beastscriptr
  - richelbilderbeek/nLTT
  - richelbilderbeek/ribir
  - richelbilderbeek/wiritttes
  - rsetienne/PBD/PBD
  - beast-dev/RBeast

before_script:
  - sudo apt-get install -qq oracle-java8-installer # Java 8
  - sudo apt-get install oracle-java8-set-default
  - ./install_beast2
  # Does not work
  #- R -e 'PKG_CXXFLAGS=-std=c++11'

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
 
after_failure:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - cat /home/travis/build/richelbilderbeek/Cer2016/..Rcheck/00install.out
  - cat /home/travis/build/richelbilderbeek/Cer2016/..Rcheck/00check.log
  - cd ~; find . | egrep "beast"
  - cd ~; find . | egrep "\.log"
  - cd ~; find . | egrep "\.trees"
  - cd ~; find . | egrep "\.xml"
  - cd ~; find . | egrep "\.xml\.state"
  - cd ~; find . | egrep "\.fasta"
  - cat /home/travis/build/richelbilderbeek/Cer2016/..Rcheck/tests/testthat/testthat.log
