---
title: "Analyse nLTT statistics"
author: "Richel Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Analyse nLTTs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Abstract

This vignette shows how analyse the nLTT statistics.

I use this to check if `rJava` is installed correctly. 
If not, this will give an error:

```{r}
options(warn = 2)
file <- wiritttes::read_file("~/Peregrine/article_0_0_0_0_0.RDa")
wiritttes::get_posterior(file, sti = 1, ai = 1, pi = 1)
```

## Setup

Loading this package

```{r}
# Analyse a subset only
rda_files <- list.files("~/Peregrine", pattern = "article_.*\\.RDa", full.names = TRUE)

# Extract the parameters
parameters <- wiritttea::collect_files_parameters(rda_files)

nltt_stats_raw <- wiritttea::read_collected_nltt_stats("~/Peregrine/collect_files_nltt_stats.csv")
nltt_stats <- nltt_stats_raw[!is.na(nltt_stats_raw$nltt_stat), ]

nltt_stats_sub <- dplyr::sample_n(nltt_stats, size = 10000)

# Merge nLTT statistics and parameters
parameters$filename <- rownames(parameters)
df <- merge(nltt_stats, parameters, by = "filename")
df$scr <- as.factor(df$scr)
df$mutation_rate <- as.factor(df$mutation_rate)
df$sequence_length <- as.factor(df$sequence_length)
df$sirg <- as.factor(df$sirg)
df$siri <- as.factor(df$siri)
df$erg <- as.factor(df$erg)
df$eri <- as.factor(df$eri)

df_sub <- merge(nltt_stats_sub, parameters, by = "filename")
df_sub$scr <- as.factor(df_sub$scr)
df_sub$mutation_rate <- as.factor(df_sub$mutation_rate)
df_sub$sequence_length <- as.factor(df_sub$sequence_length)
df_sub$sirg <- as.factor(df_sub$sirg)
df_sub$siri <- as.factor(df_sub$siri)
df_sub$erg <- as.factor(df_sub$erg)
df_sub$eri <- as.factor(df_sub$eri)
```

## Show the distribution of nLTT statistics


```{r fig.width = 7, fig.height = 7}
# ggplot2::ggplot(
# ) + ggplot2::facet_grid(. ~ sirg
# ) + ggplot2::geom_boxplot(
#   data = df,
#   ggplot2::aes(
#     x = scr,
#     y = nltt_stat
#   )
#   , alpha = 0.5
# )
# 
ggplot2::ggplot(
) + ggplot2::facet_grid(siri ~ erg
) + ggplot2::geom_density(
  data = df,
  ggplot2::aes(
    x = nltt_stat,
    fill = scr
  )
  , alpha = 0.5
)
```
