---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(RBeast)
library(wiritttea)
options(warn = 2)
#filename <- find_path("toy_example_4.RDa")
filename <- "~/Peregrine/article_1_3_0_0_1_1.RDa"
file <- wiritttes::read_file(filename)
posterior_1 <- wiritttes::get_posterior_by_index(file, 5)$trees
posterior_2 <- wiritttes::get_posterior_by_index(file, 6)$trees
posterior_3 <- wiritttes::get_posterior_by_index(file, 7)$trees
posterior_4 <- wiritttes::get_posterior_by_index(file, 8)$trees
testit::assert(RBeast::is_trees_posterior(posterior_1) == TRUE)
testit::assert(RBeast::is_trees_posterior(posterior_2) == TRUE)
testit::assert(RBeast::is_trees_posterior(posterior_3) == TRUE)
testit::assert(RBeast::is_trees_posterior(posterior_4) == TRUE)

# All same posteriors are identical
testit::assert(wiritttes::are_identical_trees_posteriors(posterior_1, posterior_1) == TRUE)
testit::assert(wiritttes::are_identical_trees_posteriors(posterior_2, posterior_2) == TRUE)
testit::assert(wiritttes::are_identical_trees_posteriors(posterior_3, posterior_3) == TRUE)
testit::assert(wiritttes::are_identical_trees_posteriors(posterior_4, posterior_4) == TRUE)

# All different posteriors are different
testit::assert(wiritttes::are_identical_trees_posteriors(posterior_1, posterior_2) == FALSE)
testit::assert(wiritttes::are_identical_trees_posteriors(posterior_1, posterior_3) == FALSE)
testit::assert(wiritttes::are_identical_trees_posteriors(posterior_1, posterior_4) == FALSE)
testit::assert(wiritttes::are_identical_trees_posteriors(posterior_2, posterior_3) == FALSE)
testit::assert(wiritttes::are_identical_trees_posteriors(posterior_2, posterior_4) == FALSE)
testit::assert(wiritttes::are_identical_trees_posteriors(posterior_3, posterior_4) == FALSE)
```

```{r fig.width=7, fig.height=7}
multiphylo_1 <- posterior_1
multiphylo_2 <- posterior_2
multiphylo_3 <- posterior_3
multiphylo_4 <- posterior_4
class(multiphylo_1) <- "multiPhylo"
class(multiphylo_2) <- "multiPhylo"
class(multiphylo_3) <- "multiPhylo"
class(multiphylo_4) <- "multiPhylo"
phangorn::densiTree(multiphylo_1, type = "cladogram", alpha = 1)
phangorn::densiTree(multiphylo_2, type = "cladogram", alpha = 1)
phangorn::densiTree(multiphylo_3, type = "cladogram", alpha = 1)
phangorn::densiTree(multiphylo_4, type = "cladogram", alpha = 1)
```
