context("read_collected_parameters")

test_that("read_collected_parameters works", {
  df <- wiritttea::read_collected_parameters()
  testthat::expect_true(class(df) == "data.frame")
  testthat::expect_true(nrow(df) == 4)
  testthat::expect_true("filename" %in% names(df))
  testthat::expect_true("rng_seed" %in% names(df))
  testthat::expect_true("sirg" %in% names(df))
  testthat::expect_true("siri" %in% names(df))
  testthat::expect_true("scr" %in% names(df))
  testthat::expect_true("erg" %in% names(df))
  testthat::expect_true("eri" %in% names(df))
  testthat::expect_true("age" %in% names(df))
  testthat::expect_true("mutation_rate" %in% names(df))
  testthat::expect_true("n_alignments" %in% names(df))
  testthat::expect_true("sequence_length" %in% names(df))
  testthat::expect_true("nspp" %in% names(df))
  testthat::expect_true("n_beast_runs" %in% names(df))
})
