#!/bin/bash
#SBATCH --time=100:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=100G
#SBATCH --job-name=collect_alignments
#SBATCH --output=collect_alignments.log

. is_peregrine

if [[ `is_peregrine` == 1 ]]; then 
  module load R/3.3.1-foss-2016a
fi

time Rscript collect_alignments.R $@
