#!/bin/bash
. is_peregrine

# Input
if [[ $# == 0 ]]; then
  echo "Please add the source superfolder as a first argument, e.g. '~/wirittte_data'"
  exit
fi

if [[ $# == 1 ]]; then
  echo "Please add the date as a second argument, e.g. '20170711'"
  exit
fi

# Variable initialization
source_superfolder=$1
echo "source_superfolder: "$source_superfolder

date=$2
echo "date: "$date

source_folder=$source_superfolder"/"$date
echo "source_folder: "$source_folder

on_peregrine=`is_peregrine`
echo "on_peregrine: "$on_peregrine

skip_install=1
echo "skip_install: "$skip_install

# Checking inputs
if [ -d $source_superfolder  ]; then
  echo "OK: source super folder is a folder"
else
  echo "ERROR: source super folder is not a folder"
  exit
fi

if [ -d $source_folder  ]; then
  echo "OK: source folder is a folder"
else
  echo "ERROR: source folder is not a folder"
  exit
fi

##########################
# Update other packages
##########################

if [[ $skip_install == 0 ]]; then
  jobid=`sbatch install_r_packages.sh | cut -d ' ' -f 4`
  echo "jobid: "$jobid
else
  echo "Skip install_r_packages"
fi

##########################
# Update this package
##########################

if [[ $skip_install == 0 ]]; then
  cmd="sbatch --dependency=afterok:$jobid install_this_r_package.sh"
  echo "cmd: "$cmd
  jobid=`$cmd | cut -d ' ' -f 4`
  echo "jobid: "$jobid
else
  echo "Skip install_this_r_package"
fi

##########################
# Collect alignment DMIDs
##########################

cmd="./collect_alignments_dmid "$source_folder" ~/parameters_"$date".csv"
if [[ $on_peregrine == 1 ]]; then 
  cmd="sbatch --dependency=afterany:$jobid "$cmd
  echo "cmd: "$cmd
  jobid=`$cmd | cut -d ' ' -f 4`
  echo "jobid: "$jobid
else
  echo "cmd: "$cmd
  eval $cmd >/dev/null
fi

##########################
# Check parameter file creation success
##########################

cmd="./collect_parameters "$source_folder" ~/parameters_"$date".csv"
if [[ $on_peregrine == 1 ]]; then 
  cmd="sbatch --dependency=afterany:$jobid "$cmd
  echo "cmd: "$cmd
  jobid=`$cmd | cut -d ' ' -f 4`
  echo "jobid: "$jobid
else
  echo "cmd: "$cmd
  eval $cmd >/dev/null
fi

##################
# Collect n taxa #
##################

cmd="./collect_n_taxa "$source_folder" ~/n_taxa_"$date".csv"
if [[ $on_peregrine == 1 ]]; then 
  cmd="sbatch --dependency=afterany:$jobid "$cmd
  echo "cmd: "$cmd
  jobid=`$cmd | cut -d ' ' -f 4`
  echo "jobid: "$jobid
else
  echo "cmd: "$cmd
  eval $cmd >/dev/null
fi


############################
# Collect n species trees
############################

cmd="./collect_n_species_trees "$source_folder" ~/n_species_trees_"$date".csv"
if [[ $on_peregrine == 1 ]]; then 
  cmd="sbatch --dependency=afterany:$jobid "$cmd
  echo "cmd: "$cmd
  jobid=`$cmd | cut -d ' ' -f 4`
  echo "jobid: "$jobid
else
  echo "cmd: "$cmd
  eval $cmd >/dev/null
fi

############################
# Collect n alignments
############################

cmd="./collect_n_alignments "$source_folder" ~/n_alignments_"$date".csv"
if [[ $on_peregrine == 1 ]]; then 
  cmd="sbatch --dependency=afterany:$jobid "$cmd
  echo "cmd: "$cmd
  jobid=`$cmd | cut -d ' ' -f 4`
  echo "jobid: "$jobid
else
  echo "cmd: "$cmd
  eval $cmd >/dev/null
fi



############################
# Collect n posteriors
############################

cmd="./collect_n_posteriors "$source_folder" ~/n_posteriors_"$date".csv"
if [[ $on_peregrine == 1 ]]; then 
  cmd="sbatch --dependency=afterany:$jobid "$cmd
  echo "cmd: "$cmd
  jobid=`$cmd | cut -d ' ' -f 4`
  echo "jobid: "$jobid
else
  echo "cmd: "$cmd
  eval $cmd >/dev/null
fi

##########################
# ESS
##########################

cmd="./collect_esses "$source_folder" ~/esses_"$date".csv"
if [[ $on_peregrine == 1 ]]; then 
  cmd="sbatch --dependency=afterany:$jobid "$cmd
  echo "cmd: "$cmd
  jobid=`$cmd | cut -d ' ' -f 4`
  echo "jobid: "$jobid
else
  echo "cmd: "$cmd
  eval $cmd >/dev/null
fi


##########################
# nLTT stats
##########################

cmd="./collect_nltt_stats "$source_folder" ~/nltt_stats_"$date".csv"
if [[ $on_peregrine == 1 ]]; then 
  cmd="sbatch --dependency=afterany:$jobid "$cmd
  echo "cmd: "$cmd
  jobid=`$cmd | cut -d ' ' -f 4`
  echo "jobid: "$jobid
else
  echo "cmd: "$cmd
  eval $cmd >/dev/null
fi

# Tested until here
exit 

##########################
# Analysis
##########################

cmd="sbatch --dependency=afterany:$jobid collect_gammas.sh"
echo "cmd: "$cmd
jobid=`$cmd | cut -d ' ' -f 4`
echo "jobid: "$jobid

cmd="sbatch --dependency=afterany:$jobid collect_nrbss.sh"
echo "cmd: "$cmd
jobid=`$cmd | cut -d ' ' -f 4`
echo "jobid: "$jobid

cmd="sbatch --dependency=afterany:$jobid collect_times.sh"
echo "cmd: "$cmd
jobid=`$cmd | cut -d ' ' -f 4`
echo "jobid: "$jobid

cmd="sbatch --dependency=afterany:$jobid analyse_esses.sh"
echo "cmd: "$cmd
jobid=`$cmd | cut -d ' ' -f 4`
echo "jobid: "$jobid

cmd="sbatch --dependency=afterany:$jobid analyse_nltt_stats.sh"
echo "cmd: "$cmd
jobid=`$cmd | cut -d ' ' -f 4`
echo "jobid: "$jobid

cmd="sbatch --dependency=afterany:$jobid analyse_time.sh"
echo "cmd: "$cmd
jobid=`$cmd | cut -d ' ' -f 4`
echo "jobid: "$jobid

cmd="sbatch --dependency=afterany:$jobid send_me_an_email.sh"
echo "cmd: "$cmd
jobid=`$cmd | cut -d ' ' -f 4`
echo "jobid: "$jobid
