#!/bin/bash

#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=100G
#SBATCH --job-name=wiritttea_baa
#SBATCH --output=wiritttea_baa.log
module load git
module load Qt
module load GCC/5.1.0
module load Boost
qmake
make
./wiritttea_peregrine `ls /data/p230198/20170208` > cout.txt
